### ISSUE TITLE
crashes and not server only

### ISSUE THREAD

**Issue by DanShu15** [AMereBagatelle/DiscordConnect#1]
After dropping the jar and starting the server it crashed as expected and generated it's config file.
The config file was populated (altho I'm not sure what the discord and minecraft message prefixes should be) and the server started fine. Bot connects no problem and reports server starts and shut downs as expected.

-The first problem is client side, I can't connect without the discord connect mod installed on the client, which then crashes even with a copy of the server config provided (which I'd prefer not to have to do anyway, obviously).

-The second problem is the server usually takes 30-40 seconds to restart at most, and now it hang for a while until it's killed, reports that it's crashed, then starts back up.

Client Log:
https://pastebin.com/sQEn4QtG
Client Crash Report:
https://pastebin.com/hGzUk2Hh
Server Log:
https://pastebin.com/hBs1zF8q
Server Crash Report:
https://pastebin.com/ME1FYcLB

**Comment by AMereBagatelle** [comment]
The first one is just me not doing things correctly, will correct that soon.  However, your server crash report looks like another mod.  Are you running a modpack?  You may want to ask the developers of `GrindEnchantments`.

**Comment by DanShu15** [comment]
I appreciate you :) I'll link this over to Grind Enchantments and keep an eye out for an update :)
Are the discord and minecraft prefixes necessary? I wasn't sure what to add there. I just put MC and D

**Comment by AMereBagatelle** [comment]
Just play with the prefixes, I'm not completely happy with how I named those.  (even I barely remember which one is which)  They shouldn't be _too_ needed for a single server however.  I would recommend setting them both, just so that people are aware where messages are coming from.

**Comment by DanShu15** [comment]
I'll mess with them :) if symbols work then maybe (D) or (MC) would be handy. To keep spam down the game chat is separate from the discord general chat.
I'm assuming once it's marked server only there won't be a need for DiscordConnect.jar to be included in the client?

**Comment by AMereBagatelle** [comment]
There will not be if I did my job correctly.  Can you try this build please?  https://github.com/AMereBagatelle/DiscordConnect/releases/tag/1.0.1

**Comment by DanShu15** [comment]
Seemed fine, I wonder if it's missingbits? Same as before, mod connects to discord and bot works great, but clients report they're missing a mod can't connect
Client:
https://pastebin.com/Hu6Qd3Dc
Server:
https://pastebin.com/y61cijiQ

**Comment by DanShu15** [comment]
That old server crash log was from weeks ago, Grind Enchantments had an issue and we took care of it. Not sure what's up now, the console reports a crash that resolves when DiscordConnect is removed, but it must not be generating an actual crash report

**Comment by AMereBagatelle** [comment]
Is this with a modpack of some sort?  It looks like you have a lot of mods loaded.

**Comment by DanShu15** [comment]
yes, a custom one I've built over the last month or so. Is it conflicting with one or several of them?

**Comment by AMereBagatelle** [comment]
It is possible that whatever modpack tool you are using (I am not too familiar with modpacks) is requiring the client and server to both have the mod.

**Comment by DanShu15** [comment]
ok, then that would have to be missingbits. Typically if the environment is set to server or client it respects that, but later when nobody is online I can test it out with and without missingbits and report it to them if that's the issue :)
If you'd like to leave the issue open I can report back with how that goes (2pm now, server quiets down at around 1am) and if not I can open a new ticket or reopen this one depending on how that goes :)
The crash is another concern and does look to be an issue with DiscordConnect (just because it clears up and we restart like lightning if it's not in, but it hangs if it is) but since it doesn't produce a crash log idk how you'd track that down.
I also noticed that the bot doesn't report the server going down until it does crash, so I'd think it was something to do with them communicating and that a way to get them to stop when the shutdown or restart command is sent might be a solution, but idk. It reports the server coming up just fine, and my console shows that it sends chat from discord to the server just fine.
I'll let you know if testing it without missingbits works out :)

**Comment by AMereBagatelle** [comment]
No problem, you can close the issue if that solves it for you :smiley:

**Comment by DanShu15** [comment]
Will do :) fingers crossed ;) We've got a good system for updating now so missingbits we can live without. I'm stoked to get it working :)
If the server dies out entirely I'll remove all my mods and test it with just DiscordConnect, then readd them in groups. Atm we have over 200 mods and libraries, so it's a delicate balance and hard to know exactly what the problem is sometimes

**Comment by DanShu15** [comment]
Sorry that took so long to test out, server's been pretty busy lately but there was only 1 person on before midday restart so I got a chance to test it.
Still haven't found a MC or Discord prefix that doesn't look better than being able to leave it blank would, is there a symbol I can put there that would work for null?

I'll link this over to missingbits, since it shouldn't be preventing logins if the mod is set to server side only.
The only remaining issue is the delay and crash report on the console reported before. After it saves all the chunks it stalls for 3 minutes then times out and is terminated automatically. The bot doesn't report the server shutting down until it's killed.

23.06 14:07:44 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM_thehallow_the_hallow): All chunks are saved
23.06 14:10:39 [Multicraft] Terminating server via signal
23.06 14:10:40 [Multicraft] Server shut down (terminating)
23.06 14:10:40 [Multicraft] Looks like a crash, check the server console. Return value: 143
23.06 14:10:40 [Multicraft] Server stopped

**Comment by AMereBagatelle** [comment]
You can use these formatting color codes to color the prefix if you think that would look better: [](https://minecraft.gamepedia.com/Formatting_codes)
I'm going to close this for now, but it can be reopened if it is in fact my mod's fault.

**Comment by DanShu15** [comment]
I had left it open because of the delay shutting down the server and the console saying it crashed and using the kill command. I'm not sure how to get more info to you on that tho if there isn't anything useful in the logs.
The crash report I linked was an old log and unrelated, and I don't see any new ones being generated

**Comment by DanShu15** [comment]
Ahh Mr Marnic from missingbits thinks that replacing 
"environment": "*", 
with 
"environment": "server",
should clear it up
The connection issue, not the crash, but I'll test it again after that to see

**Comment by AMereBagatelle** [comment]
Can you try this build, it should be better. [https://www.curseforge.com/minecraft/mc-mods/discordconnect/files/2987017](https://www.curseforge.com/minecraft/mc-mods/discordconnect/files/2987017)

**Comment by DanShu15** [comment]
my apologies, I hadn't got an email about your post so I'm just now getting it. I'll test it ASAP :)

**Comment by DanShu15** [comment]
Totally works now :)
Sorry that took so long to test, I bought Steel Series DLC and it consumed me ;) That and it seemed like someone was always on LOL

**Comment by DanShu15** [comment]
Only issue is the lockup on shutdown that makes restarts take an extra 3 or 4 minutes until the server is killed 
rver] Server thread/INFO ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
02.07 15:52:10 [Server] Server thread/INFO ThreadedAnvilChunkStorage (DIM1): All chunks are saved
02.07 15:55:04 [Multicraft] Terminating server via signal
02.07 15:55:05 [Multicraft] Server shut down (terminating)
02.07 15:55:05 [Multicraft] Looks like a crash, check the server console. Return value: 143
02.07 15:55:05 [Multicraft] Server stopped

**Comment by AMereBagatelle** [comment]
I am not absolutely sure this is the fault of my mod, but please open a extra issue for this as it is unrelated to the main issue :)
